name: Daedalus Parsiphae
description: Parser checks for Daedalus scripts

branding:
  icon: check
  color: green

inputs:
  file:
    description: File path or pattern of D file(s) or SRC file(s)
    required: true
  check-name:
    description: Name of check run
    default: Parsiphae
  cache:
    description: Cache Parsiphae built
    default: true
  token:
    description: Github authentication token
    default: ${{ github.token }}
  cleanup-token:
    description: This input is for clean up actions and should always be left at its default
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
