name: Daedalus Parsiphae
description: Parser checks for Daedalus scripts

branding:
  icon: check
  color: green

inputs:
  file:
    description: File path or pattern of D file(s) or SRC file(s)
    required: true
  token:
    description: Github authentication token
    default: ${{ github.token }}
  check_name:
    description: Name of check run
    default: Parsiphae
  cache:
    description: Cache Parsiphae built
    default: true

runs:
  using: node20
  main: dist/index.js
